### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by slowkow** [klarman-cell-observatory/cumulus#99]
CellRanger VDJ is failing with a Python error. Have you seen this before? Do you know the fix?

Error:

```
2020/06/18 02:55:12 Starting container setup.
2020/06/18 02:55:15 Done container setup.
2020/06/18 02:55:16 Starting localization.
2020/06/18 02:55:24 Localization script execution started...
2020/06/18 02:55:24 Localizing input gs://fc-32e50d9e-c0c3-465e-b0fa-b76b34358ca0/7f20566e-c6ed-4bf9-8da1-13df5ba4f866/cellranger_workflow/9e5adf71-25bb-4e75-85e6-720547fe43f8/call-generate_bcl_csv/script -> /cromwell_root/script
2020/06/18 02:55:26 Localizing input gs://fc-32e50d9e-c0c3-465e-b0fa-b76b34358ca0/kamil/2020-06-17_cellranger_input/sample_sheet.csv -> /cromwell_root/fc-32e50d9e-c0c3-465e-b0fa-b76b34358ca0/kamil/2020-06-17_cellranger_input/sample_sheet.csv
2020/06/18 02:55:29 Localization script execution complete.
2020/06/18 02:55:32 Done localization.
2020/06/18 02:55:33 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint= sccloud/cellranger@sha256:08a871f569d7441b00b307f61539c99dc774d4c30673f745956ce543a092ea44 /bin/bash /cromwell_root/script
Traceback (most recent call last):
File "<stdin>", line 10, in <module>
File "/opt/conda/lib/python3.7/site-packages/pandas/core/series.py", line 3825, in map
new_values = super()._map_values(arg, na_action=na_action)
File "/opt/conda/lib/python3.7/site-packages/pandas/core/base.py", line 1300, in _map_values
new_values = map_f(values, mapper)
File "pandas/_libs/lib.pyx", line 2228, in pandas._libs.lib.map_infer
File "<stdin>", line 10, in <lambda>
File "/opt/conda/lib/python3.7/re.py", line 192, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2020/06/18 02:55:41 Starting delocalization.
2020/06/18 02:55:42 Delocalization script execution started...
2020/06/18 02:55:42 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-32e50d9e-c0c3-465e-b0fa-b76b34358ca0/7f20566e-c6ed-4bf9-8da1-13df5ba4f866/cellranger_workflow/9e5adf71-25bb-4e75-85e6-720547fe43f8/call-generate_bcl_csv/memory_retry_rc
2020/06/18 02:55:42 Delocalizing output /cromwell_root/rc -> gs://fc-32e50d9e-c0c3-465e-b0fa-b76b34358ca0/7f20566e-c6ed-4bf9-8da1-13df5ba4f866/cellranger_workflow/9e5adf71-25bb-4e75-85e6-720547fe43f8/call-generate_bcl_csv/rc
2020/06/18 02:55:43 Delocalizing output /cromwell_root/stdout -> gs://fc-32e50d9e-c0c3-465e-b0fa-b76b34358ca0/7f20566e-c6ed-4bf9-8da1-13df5ba4f866/cellranger_workflow/9e5adf71-25bb-4e75-85e6-720547fe43f8/call-generate_bcl_csv/stdout
2020/06/18 02:55:44 Delocalizing output /cromwell_root/stderr -> gs://fc-32e50d9e-c0c3-465e-b0fa-b76b34358ca0/7f20566e-c6ed-4bf9-8da1-13df5ba4f866/cellranger_workflow/9e5adf71-25bb-4e75-85e6-720547fe43f8/call-generate_bcl_csv/stderr
2020/06/18 02:55:45 Delocalizing output /cromwell_root/run_ids.txt -> gs://fc-32e50d9e-c0c3-465e-b0fa-b76b34358ca0/7f20566e-c6ed-4bf9-8da1-13df5ba4f866/cellranger_workflow/9e5adf71-25bb-4e75-85e6-720547fe43f8/call-generate_bcl_csv/run_ids.txt
Required file output '/cromwell_root/run_ids.txt' does not exist.
```

My best guess is that this is the line with the bug:

https://github.com/klarman-cell-observatory/cumulus/blob/a401b30d4020eef44e6f517e3a2476a30cea5e25/workflows/cellranger/cellranger_workflow.wdl#L320

**Comment by slowkow** [comment]
One possible fix:

```python
df['Flowcell'] = df['Flowcell'].map(lambda x: x.rstrip('/'))
```

**Comment by slowkow** [comment]
@yihming pointed out that my sample sheet had a line with `NA` for the flowcell, and that was the cause for this error.

Users might like to receive better error messages regarding sample sheet formatting.

For example, instead of:

```
TypeError: expected string or bytes-like object
```

Users might like to see:

```
Error in sample sheet "filename.txt" on line 59: invalid value "NA" in column "Flowcell"
```
